<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SELECT(AFAN) OROMOABKHAZIANAFARAFRIK_5fa68f_1</name>
   <tag></tag>
   <elementGuidId>11829b16-24f2-45a8-8b1e-6e1bca26b2bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='workLanguageSelect']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#workLanguageSelect</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>workLanguage dropdowntitlelang validate[required]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>workLanguageSelect</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>populateSubDropdownFromServletContext('workSubLanguageSelect', 'SUBLANGUAGE', this);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SELECT(AFAN) OROMOABKHAZIANAFARAFRIKAANSAKANALBANIANAMHARICARABICARAGONESEARMENIANASSAMESEAVARICAVESTANAYMARAAZERBAIJANIBAMBARABASHKIRBASQUEBENGALI(BANGLA)BHUTANIBIHARIBISLAMABOKMÅLBOSNIANBRETONBULGARIANBURMESEBYELORUSSIANCAMBODIANCATALANCHAMORROCHECHENCHICHEWACHINESECHURCH SLAVICCHUVASHCORNISHCORSICANCREECROATIANCZECHDANISHDIVEHIDUTCHENGLISHESPERANTOESTONIANEWEFAEROESEFIJIFINNISHFRENCHFRISIANFULAHGALICIANGANDAGEORGIANGERMANGRGREEKGREENLANDICGUARANIGUJARATIHAITIANHAUSAHAWAIIHEBREWHEREROHINDIHIRI MOTUHUNGARIANICELANDICIDOIGBOINDONESIANINDONESIANINTERLINGUAINTERLINGUEINUKTITUTINUPIAKIRISHITALIANJAPANESEJAVANESEJAVANESEKANNADAKANURIKASHMIRIKAZAKHKIKUYUKINYARWANDAKIRGHIZKIRUNDIKOMIKONGOKOREANKUANYAMAKURDISHLAOTHIANLATINLATVIAN;LETTISHLIMBURGANLINGALALITHUANIANLUBA-KATANGALUXEMBOURGISHMACEDONIANMALAGASYMALAYMALAYALAMMALTESEMANXMAORIMARATHIMARSHALLESEMOLDAVIANMONGOLIANNAURUNAVAJONDEBELENDONGANEPALINORTH SOTHONORTHERN SAMINORWEGIANNORWEGIAN NYNORSKOCCITANOJIBWAORIYAOSSETIAN; OSSETICPALIPASHTO, PUSHTOPERSIANPOLISHPORTUGUESEPUNJABIQUECHUARHAETO-ROMANCEROMANIANRUSSIANSAMOANSANGROSANSKRITSARDINIANSCOTS GAELICSERBIANSERBO-CROATIANSESOTHOSETSWANASHONASICHUAN YISINDHISINGHALESESLOVAKSLOVENIANSOMALISPANISHSUNDANESESWAHILISWATISWEDISHTAGALOGTAHITIANTAJIKTAMILTATARTELUGUTHAITIBETANTIGRINYATONGATONGATURKISHTURKMENTWIUIGHURUKRAINIANURDUUZBEKUnknownVENDAVIETNAMESEVOLAPUKWALLOONWELSHWOLOFXHOSAYIDDISHYIDDISHYORUBAZHUANGZULU</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workLanguageSelect&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Make Medley/Page_MIS  WORK CREATE/iframe_Aug 10,2013_tabs1-WORKCREATE_iFrame</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='workLanguageSelect']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='workInformation']/div/div[7]/div/div/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language of Work'])[2]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Composite Type'])[1]/following::select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Class'])[1]/preceding::select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country of Reg'])[1]/preceding::select[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/select</value>
   </webElementXpaths>
</WebElementEntity>
